font=JetBrainsMono Nerd Font:size=10

[cursor]
style=beam
blink=yes

[colors]
alpha=0.85
background=0f1419
foreground=e6e1cf

# Selección (Ayu style)
selection-foreground=0f1419
selection-background=f29718

# Colores Normales
regular0=000000
regular1=ff3333
regular2=b8cc52
regular3=e7c547
regular4=36a3d9
regular5=f07178
regular6=95e6cb
regular7=ffffff

# Colores Brillantes
bright0=323232
bright1=ff6565
bright2=eafe44
bright3=fff779
bright4=68d5ff
bright5=ffa3aa
bright6=c7fffd
bright7=ffffff

[csd]
# eliminar los bordes de ventana de la app: (porque sway no los necesita)
preferred=none

[main]
# Padding
pad=12x12
