
set -g mouse on

# Cargar tema solo si existe
if-shell "test -f ~/.tmux-themepack/basic.tmuxtheme" "source-file ~/.tmux-themepack/basic.tmuxtheme"

# 1. Cambiar el prefijo a Ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# 2. División de paneles con el path actual
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# 3. Moverse entre paneles con Alt + Flechas (M es Meta/Alt)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# 4. Estética adaptable
set -g status-bg default
set -g status-style bg=default
set -g status-fg cyan
set -g status-left "#[fg=green][#S] "
# #h mostrará "Canaima" o el nombre de tu dispositivo en Termux
set -g status-right "#[fg=yellow]%H:%M #[fg=white]| #[fg=magenta]#h"

# 5. Historial y Sincronización
set -g history-limit 10000
bind y set-window-option synchronize-panes
